- name: Playbook ejecutado con Ansible-Pull
  hosts: localhost
  connection: local
  become: yes  # Si necesitas permisos de sudo
  tasks:
    - name: Hacer ping a los hosts
      ansible.builtin.ping:
